print (" Hellow world ! ")
print (" Hellow again  ")
print (" I like typing this.  ")
print (" This is fun  ")
print (' yah this is printing.  ')
print (" I'd much rather you 'not'.  ")
print (' I "siad" do not touch this .') 